name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - bumpversion
  - conda-pack
  - jupyterlab
  - pip
  - spyder<5
  - pyarrow==1.0.1
  - numpy==1.19.2
  - pandas==1.1.3
  - scipy==1.5.2
  - scikit-learn==0.23.2
  - boto3==1.16.7
  - pip:
    - parquet-tools==0.2.0
