name: pyspark_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.3
  - pip==21.1.3
  - setuptools>=52.*.*,<=57.1.0
  - wheel==0.32.3
  - findspark==1.3.0
  - ipykernel==5.3.4
  - jupyterlab==3.0.16
  - spyder==4.2.5
  - pip:
    - setuptools==57.1.0
    - parquet-tools==0.2.0
    - pyspark==3.1.2
    - matplotlib==3.2.2
    - seaborn==0.10.0
    - -r ./requirements.txt
