name: pyspark_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.3
  - pip==21.0.1
  - setuptools>=52.*.*,<=54.2.0
  - wheel==0.32.3
  - findspark==1.3.0
  - ipykernel==5.5.5
  - jupyterlab==3.0.16
  - spyder==4.2.5
  - pip:
    - setuptools==54.2.0
    - parquet-tools==0.2.0
    - pyspark==3.1.1
    - matplotlib==3.2.2
    - seaborn==0.10.0
    - -r ./requirements.txt
