name: pyspark_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.3
  - pip==21.0.1
  - setuptools>=52,<=54.2.0
  - wheel==0.32.3
  - findspark
  - ipykernel
  - jupyterlab
  - spyder<5
  - pip:
    - setuptools==54.2.0
    - parquet-tools==0.2.0
    - pyspark==3.1.1
    - -r ./requirements.txt
